INSERT INTO `countries` (`id`, `code`, `name`) VALUES
(6, 'AD', 'Andorra');
INSERT INTO `countries` (`id`, `code`, `name`) VALUES
(236, 'AE', 'United Arab Emirates');
INSERT INTO `countries` (`id`, `code`, `name`) VALUES
(1, 'AF', 'Afghanistan');
INSERT INTO `countries` (`id`, `code`, `name`) VALUES
(10, 'AG', 'Antigua & Barbuda'),
(8, 'AI', 'Anguilla'),
(3, 'AL', 'Albania'),
(12, 'AM', 'Armenia'),
(7, 'AO', 'Angola'),
(9, 'AQ', 'Antarctica'),
(11, 'AR', 'Argentina'),
(5, 'AS', 'American Samoa'),
(15, 'AT', 'Austria'),
(14, 'AU', 'Australia'),
(13, 'AW', 'Aruba'),
(2, 'AX', 'Åland Islands'),
(16, 'AZ', 'Azerbaijan'),
(28, 'BA', 'Bosnia & Herzegovina'),
(20, 'BB', 'Barbados'),
(19, 'BD', 'Bangladesh'),
(22, 'BE', 'Belgium'),
(36, 'BF', 'Burkina Faso'),
(35, 'BG', 'Bulgaria'),
(18, 'BH', 'Bahrain'),
(37, 'BI', 'Burundi'),
(24, 'BJ', 'Benin'),
(205, 'BL', 'St. Barthélemy'),
(25, 'BM', 'Bermuda'),
(34, 'BN', 'Brunei'),
(27, 'BO', 'Bolivia'),
(42, 'BQ', 'Caribbean Netherlands'),
(31, 'BR', 'Brazil'),
(17, 'BS', 'Bahamas'),
(26, 'BT', 'Bhutan'),
(30, 'BV', 'Bouvet Island'),
(29, 'BW', 'Botswana'),
(21, 'BY', 'Belarus'),
(23, 'BZ', 'Belize'),
(40, 'CA', 'Canada'),
(49, 'CC', 'Cocos (Keeling) Islands'),
(53, 'CD', 'Congo - Kinshasa'),
(44, 'CF', 'Central African Republic'),
(52, 'CG', 'Congo - Brazzaville'),
(216, 'CH', 'Switzerland'),
(56, 'CI', 'Côte d’Ivoire'),
(54, 'CK', 'Cook Islands'),
(46, 'CL', 'Chile'),
(39, 'CM', 'Cameroon'),
(47, 'CN', 'China'),
(50, 'CO', 'Colombia'),
(55, 'CR', 'Costa Rica'),
(58, 'CU', 'Cuba'),
(41, 'CV', 'Cape Verde'),
(59, 'CW', 'Curaçao'),
(48, 'CX', 'Christmas Island'),
(60, 'CY', 'Cyprus'),
(61, 'CZ', 'Czechia'),
(85, 'DE', 'Germany'),
(63, 'DJ', 'Djibouti'),
(62, 'DK', 'Denmark'),
(64, 'DM', 'Dominica'),
(65, 'DO', 'Dominican Republic'),
(4, 'DZ', 'Algeria'),
(66, 'EC', 'Ecuador'),
(71, 'EE', 'Estonia'),
(67, 'EG', 'Egypt'),
(246, 'EH', 'Western Sahara'),
(70, 'ER', 'Eritrea'),
(203, 'ES', 'Spain'),
(73, 'ET', 'Ethiopia'),
(77, 'FI', 'Finland'),
(76, 'FJ', 'Fiji'),
(74, 'FK', 'Falkland Islands'),
(143, 'FM', 'Micronesia'),
(75, 'FO', 'Faroe Islands'),
(78, 'FR', 'France'),
(82, 'GA', 'Gabon'),
(237, 'GB', 'United Kingdom'),
(90, 'GD', 'Grenada'),
(84, 'GE', 'Georgia'),
(79, 'GF', 'French Guiana'),
(94, 'GG', 'Guernsey'),
(86, 'GH', 'Ghana'),
(87, 'GI', 'Gibraltar'),
(89, 'GL', 'Greenland'),
(83, 'GM', 'Gambia'),
(95, 'GN', 'Guinea'),
(91, 'GP', 'Guadeloupe'),
(69, 'GQ', 'Equatorial Guinea'),
(88, 'GR', 'Greece'),
(200, 'GS', 'South Georgia & South Sandwich Islands'),
(93, 'GT', 'Guatemala'),
(92, 'GU', 'Guam'),
(96, 'GW', 'Guinea-Bissau'),
(97, 'GY', 'Guyana'),
(101, 'HK', 'Hong Kong SAR China'),
(99, 'HM', 'Heard & McDonald Islands'),
(100, 'HN', 'Honduras'),
(57, 'HR', 'Croatia'),
(98, 'HT', 'Haiti'),
(102, 'HU', 'Hungary'),
(105, 'ID', 'Indonesia'),
(108, 'IE', 'Ireland'),
(110, 'IL', 'Israel'),
(109, 'IM', 'Isle of Man'),
(104, 'IN', 'India'),
(32, 'IO', 'British Indian Ocean Territory'),
(107, 'IQ', 'Iraq'),
(106, 'IR', 'Iran'),
(103, 'IS', 'Iceland'),
(111, 'IT', 'Italy'),
(114, 'JE', 'Jersey'),
(112, 'JM', 'Jamaica'),
(115, 'JO', 'Jordan'),
(113, 'JP', 'Japan'),
(117, 'KE', 'Kenya'),
(120, 'KG', 'Kyrgyzstan'),
(38, 'KH', 'Cambodia'),
(118, 'KI', 'Kiribati'),
(51, 'KM', 'Comoros'),
(207, 'KN', 'St. Kitts & Nevis'),
(163, 'KP', 'North Korea'),
(201, 'KR', 'South Korea'),
(119, 'KW', 'Kuwait'),
(43, 'KY', 'Cayman Islands'),
(116, 'KZ', 'Kazakhstan'),
(121, 'LA', 'Laos'),
(123, 'LB', 'Lebanon'),
(208, 'LC', 'St. Lucia'),
(127, 'LI', 'Liechtenstein'),
(204, 'LK', 'Sri Lanka'),
(125, 'LR', 'Liberia'),
(124, 'LS', 'Lesotho'),
(128, 'LT', 'Lithuania'),
(129, 'LU', 'Luxembourg'),
(122, 'LV', 'Latvia'),
(126, 'LY', 'Libya'),
(149, 'MA', 'Morocco'),
(145, 'MC', 'Monaco'),
(144, 'MD', 'Moldova'),
(147, 'ME', 'Montenegro'),
(209, 'MF', 'St. Martin'),
(131, 'MG', 'Madagascar'),
(137, 'MH', 'Marshall Islands'),
(164, 'MK', 'North Macedonia'),
(135, 'ML', 'Mali'),
(151, 'MM', 'Myanmar (Burma)'),
(146, 'MN', 'Mongolia'),
(130, 'MO', 'Macao SAR China'),
(165, 'MP', 'Northern Mariana Islands'),
(138, 'MQ', 'Martinique'),
(139, 'MR', 'Mauritania'),
(148, 'MS', 'Montserrat'),
(136, 'MT', 'Malta'),
(140, 'MU', 'Mauritius'),
(134, 'MV', 'Maldives'),
(132, 'MW', 'Malawi'),
(142, 'MX', 'Mexico'),
(133, 'MY', 'Malaysia'),
(150, 'MZ', 'Mozambique'),
(152, 'NA', 'Namibia'),
(156, 'NC', 'New Caledonia'),
(159, 'NE', 'Niger'),
(162, 'NF', 'Norfolk Island'),
(160, 'NG', 'Nigeria'),
(158, 'NI', 'Nicaragua'),
(155, 'NL', 'Netherlands'),
(166, 'NO', 'Norway'),
(154, 'NP', 'Nepal'),
(153, 'NR', 'Nauru'),
(161, 'NU', 'Niue'),
(157, 'NZ', 'New Zealand'),
(167, 'OM', 'Oman'),
(171, 'PA', 'Panama'),
(174, 'PE', 'Peru'),
(80, 'PF', 'French Polynesia'),
(172, 'PG', 'Papua New Guinea'),
(175, 'PH', 'Philippines'),
(168, 'PK', 'Pakistan'),
(177, 'PL', 'Poland'),
(210, 'PM', 'St. Pierre & Miquelon'),
(176, 'PN', 'Pitcairn Islands'),
(179, 'PR', 'Puerto Rico'),
(170, 'PS', 'Palestinian Territories'),
(178, 'PT', 'Portugal'),
(169, 'PW', 'Palau'),
(173, 'PY', 'Paraguay'),
(180, 'QA', 'Qatar'),
(181, 'RE', 'Réunion'),
(182, 'RO', 'Romania'),
(190, 'RS', 'Serbia'),
(183, 'RU', 'Russia'),
(184, 'RW', 'Rwanda'),
(188, 'SA', 'Saudi Arabia'),
(197, 'SB', 'Solomon Islands'),
(191, 'SC', 'Seychelles'),
(212, 'SD', 'Sudan'),
(215, 'SE', 'Sweden'),
(193, 'SG', 'Singapore'),
(206, 'SH', 'St. Helena'),
(196, 'SI', 'Slovenia'),
(214, 'SJ', 'Svalbard & Jan Mayen'),
(195, 'SK', 'Slovakia'),
(192, 'SL', 'Sierra Leone'),
(186, 'SM', 'San Marino'),
(189, 'SN', 'Senegal'),
(198, 'SO', 'Somalia'),
(213, 'SR', 'Suriname'),
(202, 'SS', 'South Sudan'),
(187, 'ST', 'São Tomé & Príncipe'),
(68, 'SV', 'El Salvador'),
(194, 'SX', 'Sint Maarten'),
(217, 'SY', 'Syria'),
(72, 'SZ', 'Eswatini'),
(230, 'TC', 'Turks & Caicos Islands'),
(45, 'TD', 'Chad'),
(81, 'TF', 'French Southern Territories'),
(223, 'TG', 'Togo'),
(221, 'TH', 'Thailand'),
(219, 'TJ', 'Tajikistan'),
(224, 'TK', 'Tokelau'),
(222, 'TL', 'Timor-Leste'),
(229, 'TM', 'Turkmenistan'),
(227, 'TN', 'Tunisia'),
(225, 'TO', 'Tonga'),
(228, 'TR', 'Turkey'),
(226, 'TT', 'Trinidad & Tobago'),
(231, 'TV', 'Tuvalu'),
(218, 'TW', 'Taiwan'),
(220, 'TZ', 'Tanzania'),
(235, 'UA', 'Ukraine'),
(234, 'UG', 'Uganda'),
(232, 'UM', 'U.S. Outlying Islands'),
(238, 'US', 'United States'),
(239, 'UY', 'Uruguay'),
(240, 'UZ', 'Uzbekistan'),
(242, 'VA', 'Vatican City'),
(211, 'VC', 'St. Vincent & Grenadines'),
(243, 'VE', 'Venezuela'),
(33, 'VG', 'British Virgin Islands'),
(233, 'VI', 'U.S. Virgin Islands'),
(244, 'VN', 'Vietnam'),
(241, 'VU', 'Vanuatu'),
(245, 'WF', 'Wallis & Futuna'),
(185, 'WS', 'Samoa'),
(247, 'YE', 'Yemen'),
(141, 'YT', 'Mayotte'),
(199, 'ZA', 'South Africa'),
(248, 'ZM', 'Zambia'),
(249, 'ZW', 'Zimbabwe');